(specifications->manifest
 '("glibc-utf8-locales"
   ;;Dotfiles management
   "stow"
   "rofi"
   "gnupg"
   "pinentry-gnome3"
   "pinentry-emacs"
   "emacs-password-store"
   "emacs-use-package"
   "pcsc-lite"
   "opensc"
   ;;Hacking
   "emacs"
   "emacs-debbugs"
   "git"
   "git:send-email"
   "guile@2.2"
   "font-adobe-source-code-pro"
   "emacs-guix"
   "emacs-emojify"
   "glade"
   "racket"
   "python-virtualenv"
   "emacs-jedi"
   "python-jedi"
   ;;Devops
   "docker"
   "docker-cli"
   "docker-compose"
   ;; System Administration
   "htop"
   "curl"
   "wget"
   "the-silver-searcher"
   "openssh"
   "adb"
   "atool"
   "unzip"
   "tinc"
   "bind:utils"
   "fprintd"
   "encfs"
   "qrencode"
   "openjdk"
   "java-swt"
   "fontconfig"
   "nss-certs"
   ;; Messaging
   "mu"
   "quaternion"
   "toot"
   "dino"
   ;;# Desktop
   "gnome-tweaks"
   "gnome-calendar"
   "gnome-keyring"
   "gnome-bluetooth"
   "gnome-shell-extensions"
   "claws-mail"
   "icecat"
   "gimp"
   "inkscape"
   "luakit"
   "flatpak"


   "arc-theme"
   "arc-icon-theme"
   "dbus"
   ;; Fonts
   "font-google-noto"
   "font-terminus"
   "font-liberation"
   "font-lato"
   "font-awesome"
   "font-ibm-plex"
   ;; Media
   "vlc"
   "pavucontrol"
   "gst-plugins-bad"
   "gst-plugins-base"
   "gst-plugins-good"
   "gst-plugins-ugly"
   "gpodder"
   "shotwell"
   ;; Gaming
   "tintin++"
   "powwow"))
