(specifications->manifest
 '("glibc-utf8-locales"
   ;;# Dotfiles management
   "stow"
   "rofi"
   "gnupg"
   "pinentry-gnome3"
   "pinentry-emacs"
   "emacs-password-store"
   "emacs-use-package"
   "pcsc-lite"
   "opensc"
   ;;# Hacking
   "emacs"
   "git"
   "guile@2.2"
   "font-adobe-source-code-pro"
   "emacs-guix"
   "emacs-emojify"
   "glade"
   ;;# Devops
   "docker"
   "docker-cli"
   "docker-compose"
   ;; System Administration
   "htop"
   "curl"
   "the-silver-searcher"
   "openssh"
   "adb"
   "atool"
   "unzip"
   "tinc"
   "bind:utils"
   ;;# Desktop
   "gnome-tweaks"
   "gnome-calendar"
   "gnome-keyring"
   "claws-mail"
   ;;"icecat"
   "luakit"
   "flatpak"
   "evolution"
   "evolution-data-server"
   "gpodder"
   "shotwell"
   "jami-client-gnome"
   "dbus"
   "font-google-noto"
   "vlc"
   "toot"
   ;; Media
   "gst-plugins-bad"
   "gst-plugins-base"
   "gst-plugins-good"
   "gst-plugins-ugly"
   ;; Gaming
   "tintin++"
   "powwow"))
