export SSL_CERT_DIR="$HOME/.guix-home/profile/etc/ssl/certs"
export SSL_CERT_FILE="$HOME/.guix-home/profile/etc/ssl/certs/ca-certificates.crt"
export GIT_SSL_CAINFO="$SSL_CERT_FILE"

PATH="${PATH:+${PATH}:}~/.local/bin"

eval "$(direnv hook bash)"
